Basic Of TensorFlow

In [ ]:
pip install torch


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import torch
import math
import numpy as np

In [ ]:
data = [[1, 2], [4, 5]]
X_data = torch.tensor(data)
print(X_data)

tensor([[1, 2],
        [4, 5]])


In [ ]:
# ways to create tensor
Z = torch.ones(4,5)
print(Z)
print(Z.dtype)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
torch.float32


In [ ]:
a = torch.ones((4, 5), dtype= torch.int32)
print(a)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)


In [ ]:
del(a) 
print(a) ## After deleted a then its shows error when we have print a

NameError: ignored

In [ ]:
a= torch.tensor([[-5.1949, -6.2621, -6.2051, -5.8983, -6.3586, -6.2434, -5.8923, -6.1901,
         -6.5713, -6.9262]])

## Delete an element from torch.Tensor
b = a[a!=a[0,3]]
b


tensor([-5.1949, -6.2621, -6.2051, -6.3586, -6.2434, -5.8923, -6.1901, -6.5713,
        -6.9262])

In [ ]:
## Deleting Rows in Torch Tensor

a = torch.Tensor(
    [[0.2215, 0.5859, 0.4782, 0.7411],
    [0.3078, 0.3854, 0.3981, 0.5200],
    [0.1363, 0.4060, 0.2030, 0.4940],
    [0.1640, 0.6025, 0.2267, 0.7036],
    [0.2445, 0.3032, 0.3300, 0.4253]])

y = a[a[:, 0] > 0.2]
print(y)

tensor([[0.2215, 0.5859, 0.4782, 0.7411],
        [0.3078, 0.3854, 0.3981, 0.5200],
        [0.2445, 0.3032, 0.3300, 0.4253]])


In [ ]:
a = torch.ones(2, 3)
print(a)

b = torch.ones(2, 3) * torch.zeros(2, 3) *5
print(b)

print(a+b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# multiplication of torch
a = torch.tensor([[1,2],
                  [3,4]])
b = torch.tensor([[5,6],
                  [7,8]])
torch.mm(a, b)

tensor([[19, 22],
        [43, 50]])

In [ ]:
#Additions of torch
a = torch.randn(4)
print(a)

b = torch.rand(5, 4)
print(b)

c= torch.add(a, b, alpha=1)
print(c)

tensor([-0.6356, -2.3865, -0.5229, -0.9606])
tensor([[0.9299, 0.1052, 0.5474, 0.2506],
        [0.3652, 0.1884, 0.7517, 0.6756],
        [0.1796, 0.3175, 0.0558, 0.3254],
        [0.6978, 0.2085, 0.8484, 0.8097],
        [0.1491, 0.4997, 0.5311, 0.1841]])
tensor([[ 0.2943, -2.2813,  0.0244, -0.7100],
        [-0.2704, -2.1981,  0.2288, -0.2850],
        [-0.4560, -2.0690, -0.4671, -0.6353],
        [ 0.0622, -2.1780,  0.3254, -0.1509],
        [-0.4864, -1.8868,  0.0081, -0.7765]])


In [ ]:
t = torch.randn(1, 3)
print(t)
t1 = torch.randn(3, 1)
print()
t2 = torch.randn(1, 3)
torch.addcdiv(t, t1, t2, value=0.1)

tensor([[ 1.2720, -0.6115,  0.1879]])



tensor([[ 1.5367, -0.5145,  0.3718],
        [ 1.0043, -0.7096,  0.0018],
        [ 1.3269, -0.5914,  0.2260]])

In [ ]:
# Transpose
a = torch.randn(2, 9)
print(a)
torch.transpose(a, 0, 1)

tensor([[ 0.2999, -0.2084, -0.9781, -0.3985,  0.0846, -0.0385, -0.7214, -0.9340,
         -1.5310],
        [ 0.1145,  1.3336, -1.6650,  0.2398,  0.6673,  0.4568,  0.9606,  0.1613,
          1.9430]])


tensor([[ 0.2999,  0.1145],
        [-0.2084,  1.3336],
        [-0.9781, -1.6650],
        [-0.3985,  0.2398],
        [ 0.0846,  0.6673],
        [-0.0385,  0.4568],
        [-0.7214,  0.9606],
        [-0.9340,  0.1613],
        [-1.5310,  1.9430]])

In [ ]:
pip install functools

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Using cached functools-0.5.tar.gz (4.9 kB)
  ERROR: Failed building wheel for functools
  Running setup.py clean for functools
Failed to build functools
    Running setup.py install for functools ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p3e8m229/functools_26ec0cc96d464f66b7cfd1e514f22fa6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p3e8m229/functools_26ec0cc96d464f66b7cfd1e514f22fa6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6sknm7yw/install-record.txt --single-version-externally-managed --compile --install-head

In [ ]:
pip install tensor

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 50 kB 4.0 MB/s 
     |████████████████████████████████| 3.1 MB 13.9 MB/s 
     |████████████████████████████████| 57 kB 2.0 MB/s 
     |████████████████████████████████| 296 kB 45.5 MB/s 
     |████████████████████████████████| 80 kB 9.6 MB/s 
     |████████████████████████████████| 2.3 MB 39.6 MB/s 
     |████████████████████████████████| 49 kB 6.9 MB/s 
     |████████████████████████████████| 251 kB 48.2 MB/s 
     |████████████████████████████████| 74 kB 1.5 MB/s 
  Created wheel for tensor: filename=tensor-0.3.6-py3-none-any.whl size=71568 sha256=25e6f5b92523b7528ef17c844b837e78d7b712ecbb4bbe86ba016c1958664bdf
  Stored in directory: /root/.cache/pip/wheels/66/49/9d/4c43e89065768fec7ab631d87d9ac21d619b6b0b3d45de1714
  Created wheel for construct: filename=construct-2.10.68-py3-none-any.whl size=59227 sha256=309f6776f1beccde490dd3ee63e5c5e4c5e18d4

In [ ]:
# multipilications of 3d matrix
tensor1 = torch.randn(10,3,4)

tensor2 = torch.randn(10,4,5)

torch.matmul(tensor1, tensor2)

tensor([[[-5.5096, -2.5385,  2.6057, -2.1348,  2.1247],
         [-4.7158, -3.7439, -0.6670,  1.0075,  1.1335],
         [-0.6418,  1.4527,  0.3311,  1.0737, -2.3924]],

        [[ 3.0895, -1.2942,  0.4172,  4.0271,  1.0982],
         [ 1.0343,  1.3979, -4.4334,  5.0689,  0.6810],
         [-2.6522,  0.7491, -1.0458,  0.5297, -0.2492]],

        [[ 1.7240,  1.5765, -0.6755,  2.7695,  2.4351],
         [-0.2088, -1.7583, -0.4197, -2.2273, -1.4908],
         [-0.9130, -1.9423, -2.5626,  1.0984, -1.2507]],

        [[-0.0783, -1.9347,  0.6697, -1.5958, -1.4109],
         [ 0.0900,  0.9616, -1.4137, -0.0849,  0.5786],
         [-0.5074,  0.6131,  1.9117,  2.3222,  1.4027]],

        [[ 1.2375, -0.9668, -2.6222,  0.2414,  1.5779],
         [-0.7586, -0.4048,  2.9679, -1.7032, -0.4468],
         [-4.4229, -0.7239,  3.5951,  1.3591, -1.3586]],

        [[-1.5778,  1.2308,  1.4849, -5.3333,  2.2825],
         [-1.3358,  0.4695, -2.5003, -0.5748,  1.0964],
         [-0.2290, -2.1960, -3.3533,  

In [ ]:
a = torch.randn(3, 5)
b = torch.randn(5, 9) 
print(a)
print(b)

tensor([[-0.5807, -1.8043,  1.1848, -0.3676, -0.2289],
        [ 0.3841,  0.7871, -1.3551,  0.6142,  0.9675],
        [-1.9165, -0.0682,  0.1591,  0.8380,  1.0279]])
tensor([[-1.6073, -2.0620,  0.9902,  0.2007, -1.0102, -0.9114, -0.7133, -0.9107,
          0.2569],
        [-1.4476,  0.5601,  2.2683, -0.2001, -0.2253,  0.9605,  1.1885, -0.1156,
          0.9119],
        [ 2.9280, -0.1091, -0.0041,  0.0629, -1.6312, -0.1928,  0.5039,  1.4286,
         -1.1221],
        [-0.9253, -0.4978,  0.1772,  0.6494, -0.5136, -0.2438, -0.3823, -0.1395,
          0.2948],
        [ 0.5168, -0.8286,  0.3935,  1.7352, -0.4638,  0.4991, -0.0395,  0.8228,
          0.2162]])


In [ ]:
pip install tf

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for tf: filename=tf-1.0.0-py3-none-any.whl size=1285 sha256=9173f0ae0d3a3297956bbd5ecc77b1ce7a9b5f765fe5382b507c8fe572d5bf25
  Stored in directory: /root/.cache/pip/wheels/db/c7/58/cca67875b41ff853d3fdaa20b54a780ef2e045fbcacaef1ee3
Successfully built tf


In [ ]:
import tensorflow as tf
a = tf.Variable(initial_value=[[0, 0, 0, 0],[2, 2, 2, 2],[1, 1, 1, 1]]) 
b = tf.stack([a[0], a[2]])
c = tf.stack([a[0], a[1]])
print(a)
print(b)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [2, 2, 2, 2],
       [1, 1, 1, 1]], dtype=int32)>
tf.Tensor(
[[0 0 0 0]
 [1 1 1 1]], shape=(2, 4), dtype=int32)


In [ ]:
A = torch.zeros(2, 3, names= ('N', 'C'))
A

tensor([[0., 0., 0.],
        [0., 0., 0.]], names=('N', 'C'))

In [ ]:
tensor1 = torch.randn(10,3,4)
tensor2 = torch.randn(10,4,5)

c= torch.matmul(tensor1, tensor2)
print(c)

torch.aminmax(torch.tensor(c))

tensor([[[ 2.8262, -0.0726, -2.6922,  0.5830, -0.0879],
         [-3.9973,  3.4952,  1.4925,  0.7779, -2.9439],
         [-3.1483,  1.9090,  0.7571,  0.6202, -2.5945]],

        [[-1.2987,  1.8007, -1.0808,  3.4742, -2.8635],
         [ 4.7337, -1.4570, -1.6370, -0.6989,  5.5131],
         [ 0.4138, -0.5372, -0.1161, -0.6642,  0.5728]],

        [[-0.1487,  0.9130,  0.1701,  0.3565, -0.1340],
         [ 2.8415,  3.5647,  2.5061,  0.6771, -1.4570],
         [-1.4174, -2.4689, -2.3766,  0.1448, -0.5754]],

        [[ 0.0341, -0.6894,  0.8794, -1.9717, -1.9035],
         [-1.4477,  0.0937,  0.0280,  3.2440,  3.1393],
         [-1.7049, -2.3928,  3.4973, -2.8269, -4.5229]],

        [[ 1.4007, -1.5283, -0.4425, -1.4708,  2.2114],
         [ 0.5855, -1.1076, -0.6525, -1.1745,  1.2420],
         [ 1.0121, -4.4782,  0.0620, -1.8795,  6.5535]],

        [[ 2.2268,  3.2241, -3.2421, -0.4096,  1.3557],
         [ 0.0629, -1.1906,  0.7482,  0.7330, -0.6171],
         [ 0.2008,  3.5414,  3.7220, -

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  import sys


torch.return_types.aminmax(
min=tensor([[[-1.2987, -1.5283, -3.2421, -2.9847, -2.8635],
         [-3.9973, -3.5442, -1.6370, -1.1745, -2.9439],
         [-3.1483, -4.4782, -3.2046, -2.8269, -4.5229]]]),
max=tensor([[[2.8262, 5.2966, 3.1994, 3.4742, 2.6708],
         [4.7337, 4.3437, 2.9912, 3.6572, 5.6619],
         [5.3226, 7.8928, 3.7220, 2.0542, 6.5535]]]))

In [ ]:
torch.aminmax(torch.tensor([1, -3, 5, torch.nan]))

torch.return_types.aminmax(
min=tensor(-3),
max=tensor(5))

In [ ]:
 t = torch.arange(10).view(2, 5)
 t

 t.aminmax(dim=0, keepdim=True)

torch.return_types.aminmax(
min=tensor([[0, 1, 2, 3, 4]]),
max=tensor([[5, 6, 7, 8, 9]]))

In [ ]:
a = torch.randn(3, 5)
print(a)
a.aminmax(dim=0, keepdim=True)

tensor([[ 0.1706,  1.5834, -0.9866,  0.5686,  0.3274],
        [ 1.4340, -2.0955, -0.8827, -0.0631,  0.0470],
        [ 0.5672, -1.2155, -0.7901, -0.0452, -0.8255]])


torch.return_types.aminmax(
min=tensor([[ 0.1706, -2.0955, -0.9866, -0.0631, -0.8255]]),
max=tensor([[ 1.4340,  1.5834, -0.7901,  0.5686,  0.3274]]))

In [ ]:
a = torch.rand(5,2).bool()
a

tensor([[True, True],
        [True, True],
        [True, True],
        [True, True]])

In [ ]:
torch.all(a, dim=1)

tensor([True, True, True, True])

In [ ]:
torch.all(a, dim=0)

tensor([True, True])

In [ ]:
a = torch.randn(7, 3) <0
a
torch.max(a, 1)

torch.return_types.max(
values=tensor([False,  True,  True, False, False,  True,  True]),
indices=tensor([0, 0, 0, 0, 0, 1, 0]))

In [ ]:
torch.any(a, 1)

tensor([ True,  True, False,  True,  True,  True,  True])

In [ ]:
torch.any(a, 0)

NameError: ignored

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

data = pd.read_csv('sampledata.csv',encoding="ISO-8859-1")
data

Unnamed: 0        Unnamed: 1      Unnamed: 2 Unnamed: 3  \
0                   Name             Sport     Nationality        Age   
1         ABBAS Muhammad     Alpine Skiing        Pakistan         23   
2          ABBOTT Jeremy    Figure Skating   United States         24   
3           ABLAEV Enver  Freestyle Skiing         Ukraine         30   
4     ABRAMASHVILI Iason     Alpine Skiing         Georgia         21   
...                  ...               ...             ...        ...   
2602         ZUEV Stepan     Alpine Skiing          Russia         21   
2603   ZURBRIGGEN Silvan     Alpine Skiing     Switzerland         28   
2604   ZUZULOVA Veronika     Alpine Skiing        Slovakia         25   
2605  ZVARICOVA Veronika          Biathlon  Czech Republic         21   
2606  ZVEJNIEKS Kristaps     Alpine Skiing          Latvia         17   

     Unnamed: 4 Unnamed: 5  
0         Wt kg         Ht  
1            55        168  
2           NaN        175  
3            68        169  
4            82        176  
...         ...        ...  
2602         90        189  
2603         94        185  
2604         72        172  
2605         62        176  
2606         87        185  

[2607 rows x 6 columns]

In [ ]:
import torch
def describe_tensor(tensor, Name= ''):
  print('name: ', Name)
  print(Age)